"""
Streamlit UI Components for the premium Planner Multi-Agent application.
"""

import streamlit as st

def render_navbar():
    """Renders the top navigation bar."""
    st.markdown(
        """
        <div class="navbar">
            <a href="#" class="nav-logo">
                <div class="nav-logo-icon">P</div>
                Planner Multi-Agent
            </a>
            <div class="nav-links">
                <a href="#" class="active">Home</a>
                <a href="https://github.com/Dixit-Anmol/planner-multi-agent#readme" target="_blank">How it Works</a>
                <a href="https://github.com/Dixit-Anmol/planner-multi-agent" target="_blank">About</a>
                <a href="/" class="nav-btn">New Query</a>
            </div>
        </div>
        <div class="navbar-spacer"></div>
        """,
        unsafe_allow_html=True
    )

def render_hero():
    """Renders the Hero Title & Subtitle."""
    st.markdown(
        """
        <div class="hero fade-in-up">
            <h1>Ask Anything, Get <span>Smart Answers</span> <span class="hero-sparkle">✨</span></h1>
            <p>Our AI multi-agent system plans, researches, verifies and delivers accurate, high-quality responses.</p>
        </div>
        """,
        unsafe_allow_html=True
    )

def render_suggestion_chips():
    """Renders the suggestion chips below the text area and returns the clicked value."""
    st.markdown('<div class="spacer-sm"></div>', unsafe_allow_html=True)
    
    # Render pure visual chips as suggested in the prompt and screenshot
    st.markdown(
        """
        <div class="chips-row fade-in delay-1">
            <span class="chip-label">Try asking about:</span>
            <a class="chip" href="?query=AI+in+healthcare">AI in healthcare</a>
            <a class="chip" href="?query=Future+of+renewable+energy">Future of renewable energy</a>
            <a class="chip" href="?query=Space+exploration">Space exploration</a>
            <a class="chip" href="?query=Stock+market+outlook">Stock market outlook</a>
            <a class="chip" href="?query=Digital+marketing+trends">Digital marketing trends</a>
        </div>
        """,
        unsafe_allow_html=True
    )

def render_progress_view(step: int):
    """
    Renders progress updates based on workflow state.
    Steps:
    0: Input submitted / idle
    1: Planner (Thinking/Planning)
    2: Executor (Researching & Generating answers)
    3: Verifier (Evaluating quality)
    4: Finished
    """
    if step == 0:
        return
        
    steps_data = [
        ("🧠", "Understanding your question...", 1),
        ("📋", "Planning the best approach...", 1),
        ("🌐", "Researching reliable sources...", 2),
        ("🤖", "Generating answers...", 2),
        ("✅", "Verifying quality and correctness...", 3),
        ("✨", "Finalizing response...", 4)
    ]
    
    st.markdown('<div class="progress-container fade-in">', unsafe_allow_html=True)
    st.markdown('<div class="progress-title">Our AI Agents are Working for You</div>', unsafe_allow_html=True)
    st.markdown('<div class="progress-subtitle">Each agent plays a specialized role to bring you the best answer.</div>', unsafe_allow_html=True)
    
    # Progress Bar value based on step
    progress_val = min(int(step * 25), 100)
    st.progress(progress_val)
    
    st.markdown('<div class="spacer-sm"></div>', unsafe_allow_html=True)
    
    for icon, label, step_trigger in steps_data:
        if step > step_trigger:
            st.markdown(f'<div class="step-item done">✔️ {icon} {label}</div>', unsafe_allow_html=True)
        elif step == step_trigger:
            st.markdown(f'<div class="step-item active">🔄 {icon} {label}</div>', unsafe_allow_html=True)
        else:
            st.markdown(f'<div class="step-item" style="opacity: 0.4;">⏳ {icon} {label}</div>', unsafe_allow_html=True)
            
    st.markdown('</div>', unsafe_allow_html=True)

def render_disclaimer():
    """Renders the standard product footer disclaimer."""
    st.markdown(
        """
        <div class="disclaimer fade-in delay-4">
            <span class="disclaimer-icon">⚠️</span>
            <span><b>Disclaimer:</b> This response is generated by our AI multi-agent system for informational purposes only. Please verify critical information independently.</span>
        </div>
        """,
        unsafe_allow_html=True
    )

def render_footer():
    """Renders the premium footer."""
    st.markdown(
        """
        <div class="app-footer">
            <div class="footer-brand">Planner Multi-Agent</div>
            <div class="footer-tagline">Powered by advanced AI agents to deliver accurate, verified, and actionable insights.</div>
            <div class="footer-copy">© 2026 Planner Multi-Agent System. All rights reserved.</div>
        </div>
        """,
        unsafe_allow_html=True
    )
